# Generated by Django 5.2.8 on 2025-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='category',
            field=models.CharField(choices=[('history', 'Исторические'), ('beach', 'Пляжные'), ('modern', 'Мегаполисы'), ('nature', 'Природные'), ('culture', 'Культурные')], default='culture', max_length=20),
        ),
    ]
